# Makefile for Maze Program
# Description : The makefile is to clean ./src folder

CC = gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb
LIB = ./../lib/
TEST = ./../testing/


#Make the Maze Program


.PHONY : clean

#clean function : deletes all temporary files
clean :
	rm -f *~
	rm -f *#
	rm -f *.o
	rm -f core.*
	rm -f vgcore.*
	rm -f *.gch
	@echo "Unnecessary Files were deleted from ./src."




